<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">
<?php
    $name = $form->get('cedula');
    echo $formLabel->openTag()." Codigo / Cedula : ";
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>    
<div class="control-group">
<?php
    $name = $form->get('nombre');
    echo $formLabel->openTag()." Nombres: ";
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>    
<div class="form_element">
<?php
    $select = $form->get('idRol');
    echo $formLabel->openTag().'Rol';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</div>
<hr />
<div class="control-group">
<?php
    $name = $form->get('clave1');
    echo $formLabel->openTag()."Digite su clave: ";
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>    
<div class="control-group">
<?php
    $name = $form->get('clave2');
    echo $formLabel->openTag()."Confirme su clave: ";
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>    
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    