<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<table>
<tr><td>Nombre del modulo:
<?php
    $name = $form->get('nombre');
    echo $formLabel->openTag()."";
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
    </td></tr>
</table>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('agregar')) ?>
</div>  
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<?php echo $this->form()->closeTag() ?>

<div id="dialog"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>id/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php 
$this->ncol='null,';
echo $this->render('layout/tabla_p') ?>
    
</table>
<?php echo $this->render('layout/iregresar') ?> 