<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i/1',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

Pagar días no reportados
<?php
    $select = $form->get('check1');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>     
<hr />
Restar días conceptos asumidos por la empresa
<?php
    $select = $form->get('check2');
    echo $this->formCheckbox($select);
?><span class="lbl"></span>      
      
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    