<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'h',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>

<div class="row">
<div class="col-sm-4"> 
    <?php
      $select = $form->get('idCcosM1');
      echo $formLabel->openTag().' El sabado es dia habil para';
      echo $formLabel->closeTag();
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
   ?>   
</div>    
<div class="col-sm-4">
    <?php
      $select = $form->get('idCcosM2');
      echo $formLabel->openTag().' El domingo es dia habil para';
      echo $formLabel->closeTag();
      echo $this->formSelect($select);
      echo $this->formElementErrors($select);
   ?>   
</div> 

</div>
    
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>
<?php echo $this->render('layout/iregresar') ?> 