<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<div class="row">    
   <div class="col-sm-4">Modulo:<br />                        
<?php
    $name = $form->get('nombre');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>       
</div>
</div>
<br />
<div class="row">    
   <div class="col-sm-4">Modelo:<br />                        
<?php
    $name = $form->get('nombre1');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
<div class="col-sm-4">Controlador:<br />                        
<?php
    $name = $form->get('nombre2');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>    
<div class="col-sm-4">Vista:<br />                        
<?php
    $name = $form->get('apellido1')->setAttribute("value","list");
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>
</div> 

<?php
    $select = $form->get('tipo');
    echo $formLabel->openTag().'Grupo de opciones';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
</td></tr>
</table>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('agregar')) ?>
</div>  
<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<?php echo $this->form()->closeTag() ?>

<div id="dialog"></div>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["link"] ?></td>   
            <td><?php echo $dato["nomgop"] ?></td>   
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>id/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php 
$this->ncol='null,null,null,';
echo $this->render('layout/tabla_p') ?>
    
</table>
<?php echo $this->render('layout/iregresar') ?> 