<?php echo $this->render('layout/titulo') ?>

<a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a"><?php echo $this->render('layout/inuevo') ?></a>
<hr />
<strong>Valor de materiales : $vlrMat</strong>
<br />
<strong>Valor de servicios  : $vlrSer</strong>
<br />
<strong>Valor total  : $vlrTotal</strong>
<br />
<strong>Margen cotización  : $margenC</strong>
<hr />
<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php echo $dato["variable"] ?></td>
            <td><?php echo $dato["formula"] ?></td>        
            <td>
              <?php if ($dato["variable"]=='') { ?>  
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>g/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/iCal') ?> </a>
               <?php if ($dato["idGrupo"]>0) { 
                  echo $this->render('layout/iokm');
               } 
             } ?>                                                
            </td>                                    
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>a/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieditar') ?> </a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?><?php echo $this->lin?>d/<?php echo $dato["id"]?>"> <?php echo $this->render('layout/ieliminar') ?> </a>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
        
<?php 
$this->ncol='null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>        
    
