<?php echo $this->render('layout/titulo') ?>

<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<strong>Valor de materiales : $vlrMat</strong>
<br />
<strong>Valor de servicios  : $vlrSer</strong>
<br />
<strong>Valor total  : $vlrTotal</strong>
<br />
<strong>Margen cotización  : $margenC</strong>
<hr />
<div class="control-group">
<?php
    $name = $form->get('nombre');
    echo $formLabel->openTag().$name->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
</div>    
<?php
    $name = $form->get('variable');
    echo $formLabel->openTag()."Variable: ";
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
?>
<hr />
<?php 
echo $formLabel->openTag().'Formulación:';
echo $formLabel->closeTag();
echo ($this->formRow($form->get('formula')
          ->setAttribute("id","validacion") )); ?>


<div class="control-group">    
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
</div>
<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>

<?php echo $this->render('layout/iregresar') ?>    