<?php echo $this->render('layout/titulo') ?>
<?php echo $this->render('layout/treview') ?>

<?php
$form = $this->form;
$form->prepare();
?>

<?php 
/////// SEDES /////////
$arbol   = '';
$idM0   = 0;
$idM1   = 0;
$idM2   = 0;
foreach ($this->datArb as $dato){ 
    if ($idM0!=$dato['id'])
    {
      $idM0 = $dato['id'];  
      $id0 = '0.'.$idM0;  
      if ($arbol=='')
          $arbol = '{ id:'.$id0.', pId:0, name:"'.$dato['nombre'].'", icon:"'.$this->basePath().'/img/casa.png" }';    
      else 
          $arbol = $arbol.',{ id:'.$id0.', pId:0, name:"'.$dato['nombre'].'", icon:"'.$this->basePath().'/img/casa.png" }';                           
    }
    if ($idM1!=$dato['idM1'])
    {
       $idM1 = $dato['idM1'];
       $id1 = '1.'.$idM1;  
       $arbol = $arbol.',{ id:'.$id1.', pId:'.$id0.', name:"'.$dato['nomMod1'].'", icon:"'.$this->basePath().'/img/submenu.png" }';                           
    }    
    if ($idM2!=$dato['idM2'])
    {
       $idM2 = $dato['idM2'];
       $id2 = '2.'.$idM2.'9';  // Toca agregarle un 9, porque el 0 tiene problemas 
       $arbol = $arbol.',{ id:'.$id2.', pId:'.$id1.', name:"'.$dato['nomMod2'].'", icon:"'.$this->basePath().'/img/items.png" }';                           
    }    

    //$idM2 = $dato['idM2'];
    //$arbol = $arbol.',{ id:'.$idM2.', pId:'.$idM1.', name:"'.$dato['nomMod2'].'", icon:"'.$this->basePath().'/img/casa.png" }';                           
}
?>

<script type="text/javascript">
var setting = {
    data: {
      simpleData: {
      enable: true
      }
    },
    callback: {
	beforeClick: beforeClick,
        }                        
    };
var zNodes =[
   <?php echo $arbol ?>
];


	$(document).ready(function(){
		var t = $("#treeDemo");
		t = $.fn.zTree.init(t, setting, zNodes);
		demoIframe = $("#testIframe");
	
	});

	function loadReady() {
		var bodyH = demoIframe.contents().find("body").get(0).scrollHeight,
		htmlH = demoIframe.contents().find("html").get(0).scrollHeight,
		maxH = Math.max(bodyH, htmlH), minH = Math.min(bodyH, htmlH),
		h = demoIframe.height() >= maxH ? minH:maxH ;
		if (h < 530) h = 530;
		demoIframe.height(h);
	}

<?php 
$this->idModal = "agregarCom";
$this->botModal = "Administración de componentes"; ?>
var log, className = "dark";
function beforeClick(treeId, treeNode, clickFlag) {		
    ///// Cargando componentes y elementos del sistema seleccionado ///////   
    // Nodo hijo
    var id = treeNode.id;
    var mensaje = ""+treeNode.id+"";
    var nivel = mensaje.substr( 0,1);    
    var id = mensaje.substr( mensaje.indexOf(".")+1,10);              

    demoIframe.attr("src","<?php echo $this->basePath() ?><?php echo $this->lin?>o/"+id);
    //return true;
        
    return (treeNode.click != false);
}                
</script>

<?php
$form->setAttributes(array(
    'action' => $this->url.$this->lin.'e',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>

<div class="row">
  <div class="col-sm-2">Buscar por la cedula:<br />              
   <?php
    $name = $form->get('cedula');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
   ?>
  </div>
  <div class="col-sm-2"><br />              
    <?php echo $this->formElement($form->get('buscar')) ?>
  </div>
</div> 

  

<?php echo $this->form()->closeTag() ?>    

<!-- Inicio listado por centros de costos-->

<div class="row">

<TABLE border=0 height=600px align=left>
 <TR>
  <TD width=360px align=left valign=top style="BORDER-RIGHT: #999999 1px dashed">
   <!-- Render lineas, grupos y sistemas -->
   <div style="float:left;" class="zTreeDemoBackground left">
     <ul id="treeDemo" class="ztree"></ul>
   </div>                        
   

<?php
// Variables para envio de datos excel maestro
$this->spdf      = 1;// Activa la salida por PDf
$this->modelo    = 'new \Principal\Model\AlbumTable($con)';// Modelo de consulta
$this->funcion   = '$m->getEmpMG('."''".')';
$this->columnas  = "CEDULA, NOMBRE, APELLIDO, CODIGO CARGO, CARGO, CODIGO C.C., CENTRO DE COSTO,SUELDO, SALUD, PENSION,CESANTIAS, ARL, APORTES VOLUNTARIOS, APORTES AFC, TIPO DE CONTRATACION, TIPO DE EMPLEADO, GRUPO DE NOMINA,AUTOMATICO 1,AUTOMATICO 2,AUTOMATICO 3,AUTOMATICO 4";// Columnas
$this->datos     = "CedEmp,nombre,apellido,codCar,nomCar,idCcos,nomCcos,sueldo,nomSal,nomPen,nomCes,nomArp,nomFav,nomFafc,nomTcon,nomTemp,nomGrup,nomTau1,nomTau2,nomTau3,nomTau4";// Datos de impresion
$this->filtros   = 1;
echo $this->render('layout/excel') ?>

  </TD>
  <TD width=770px align=left valign=top><IFRAME ID="testIframe" Name="testIframe" FRAMEBORDER=0 SCROLLING=AUTO width=100%  height=600px ></IFRAME></TD> 
 </TR>
</TABLE>
</div>

<?php 
$this->ncol='null,null,null,null,';
echo $this->render('layout/tabla_tb') ?>        

<?php echo $this->render('layout/iregresar') ?>    

