<?php echo $this->render('layout/titulo') ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'i',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<?php
    $select = $form->get('tipo');
    echo $formLabel->openTag().'Modulo padre';
    echo $formLabel->closeTag();
    echo $this->formSelect($select);
    echo $this->formElementErrors($select);
?>
<div id="resultado"></div>
<?php    
    $name = $form->get('id');
    echo $this->formInput($name);    
?>    
<?php echo $this->form()->closeTag() ?>


<script>
$(function () {
  $("#tipo").change(function () {
    var a = $("#id").val();
    var b = $("#tipo").val();
           var parametros = {
                "id1"  : a,                
                "id2"  : b,                
              }; 
            $.ajax({
                data:  parametros,
                url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>p',
                type:  'post',
                beforeSend: function () {
                    $("#resultado").html('<h3 class="header smaller lighter grey"><i class="icon-spinner icon-spin orange bigger-125"></i></h3>Por favor espere...');
                },
               success:  function (response) {
                    $("#resultado").html(response);                    
               }
             });          
     })
  })
</script>



<?php echo $this->render('layout/iregresar') ?> 