<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'a',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
?>
<?php echo $this->form()->closeTag() ?>

<h3 class="header smaller lighter blue">Opciones de menu</h3>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nomM2"] ?></td>
            <td><?php
                   $select = $form->get('check1');
                   $select->setAttribute("id",'n_'.$dato["idM2"]); 
                   $select->setAttribute("value",$dato["nuevo"]);                    
                   echo $this->formCheckbox($select);
                   ?><span class="lbl"></span>
            </td>
            <td><?php
                   $select = $form->get('check1');
                   $select->setAttribute("id",'m_'.$dato["idM2"]); 
                   $select->setAttribute("value",$dato["modificar"]);                    
                   echo $this->formCheckbox($select);
                   ?><span class="lbl"></span>
            </td>
            <td><?php
                   $select = $form->get('check1');
                   $select->setAttribute("id",'e_'.$dato["idM2"]); 
                   $select->setAttribute("value",$dato["eliminar"]);                    
                   echo $this->formCheckbox($select);
                   ?><span class="lbl"></span>
            </td>            
            <td><?php
                   $select = $form->get('check1');
                   $select->setAttribute("id",'a_'.$dato["idM2"]); 
                   $select->setAttribute("value",$dato["aprobar"]);                    
                   echo $this->formCheckbox($select);
                   ?><span class="lbl"></span>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
        
<script>
$(function (){
  // Recorrer las clases de check para verificar estado del permiso
  $('.check').click(function(){
      
    var a = $("#id").val();
    var b = $("#tipo").val();
    var c = $("#idM").val();        
    var ida = $(this).attr('id');
    var permiso = 0    
    if($("#"+ida).is(':checked')) 
       {
          permiso = 1
       }else{ 
          permiso = 0
       }        
       var parametros = {
                "idrol"    : a,                
                "permiso"  : permiso,                
                "idm1"     : b,               
                "idm2"     : c,               
                "idm3"     : ida,               
              }; 
       $.ajax({
                data:  parametros,
                url:   '<?php echo $this->basePath() ?><?php echo $this->lin?>og',
                type:  'post',
                success:  function (response) {
                    alert('Guardado')
               }
       }); // FIn ajax                       
  });// Fin clic check
})
</script>

<div id="resultado3"></div>
        
        
<?php 
$this->ncol='null,null,null,';
echo $this->render('layout/tabla_tb') ?>        
    
