<?php
$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    'action' => $this->url.$this->lin.'o/'.$this->id,
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Abriendo etiqueta del formulario
echo $this->form()->openTag($form);
    $name = $form->get('id');
    echo $this->formInput($name);    

?>

<h3 class="header smaller lighter blue">Opciones de menu</h3>

<?php echo $this->render('layout/tabla_c') ?>

    <?php foreach ($this->datos as $dato){ ?>
        <tr>
            <td><?php echo $dato["nombre"] ?></td>
            <td><?php
                   $select = $form->get('check1');
                   $select->setAttribute("id",'n_'.$dato["id"]); 
                   $select->setAttribute("name",'n_'.$dato["id"]); 
                   $select->setAttribute("value",$dato["nuevo"]);                    
                   echo $this->formCheckbox($select);
                   ?><span class="lbl"></span>
            </td>
            <td><?php
                   $select = $form->get('check1');
                   $select->setAttribute("id",'m_'.$dato["id"]); 
                   $select->setAttribute("name",'m_'.$dato["id"]); 
                   $select->setAttribute("value",$dato["modificar"]);                    
                   echo $this->formCheckbox($select);
                   ?><span class="lbl"></span>
            </td>
            <td><?php
                   $select = $form->get('check1');
                   $select->setAttribute("id",'e_'.$dato["id"]); 
                   $select->setAttribute("name",'e_'.$dato["id"]); 
                   $select->setAttribute("value",$dato["eliminar"]);                    
                   echo $this->formCheckbox($select);
                   ?><span class="lbl"></span>
            </td>            
            <td><?php
                   $select = $form->get('check1');
                   $select->setAttribute("id",'a_'.$dato["id"]); 
                   $select->setAttribute("name",'a_'.$dato["id"]); 
                   $select->setAttribute("value",$dato["aprobar"]);                    
                   echo $this->formCheckbox($select);
                   ?><span class="lbl"></span>
            </td>            
        </tr>
    <?php } ?>
        
<?php echo $this->render('layout/tabla_p') ?>
        

<div class="form-actions">    
  <?php echo $this->formElement($form->get('send')) ?>
</div>    
<?php echo $this->form()->closeTag() ?>